version: '3'
services:
  app:
    container_name: urlshortener-service
    image: urlshortener-service:v1
    build: .
    links:
      - redis
    ports:
    -  "8080:8080"
    volumes:
    - ~/docker/urlshortener:/urlshortener-service/logs
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
    - "6379:6379"